### ISSUE TITLE
release 2.8 issues

### ISSUE THREAD

**Issue by slapin** [godotengine/godot-blender-exporter#241]
I hope you guys know, but just in case - physics and material export do not work for release version of blender-2.80. Looks like either data structures changed or it was not working from start (with 2.8). Enabling material or physics produce exporter crashes.

**Comment by Jason0214** [comment]
Can I ask what platform are you using? 

The [CI test](https://travis-ci.org/godotengine/godot-blender-exporter/builds/565831588?utm_source=github_status&utm_medium=notification) for blender2.8 which runs on Linux is passing, so it should be fine. 

I also tested on OSX, there is no material or physics related crash. But guess what on OSX  when I run shape key exporting, there is some random segfault from blender, not sure if that's also what you have seen.

**Comment by slapin** [comment]
I'm on Linux. I found that using vector math nodes and color mix nodes
produce the problem. If I just add textures, no problem so far.

Physics error:
[INFO]: Exporting scene: Scene
[INFO]: Exporting 522 objects
[INFO]: Exporting Blender object: floor
[INFO]: Exporting Blender object: closet_walls
[INFO]: Exporting Blender object: outside_door_wide.001
[INFO]: Exporting Blender object: door1_oneside.001
[INFO]: Exporting Blender object: door1_oneside.002
Traceback (most recent call last):
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/__init__.py",
line 198, in execute
    return export_godot.save(self, context, **keywords)
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/export_godot.py",
line 318, in save
    exp.export()
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/export_godot.py",
line 267, in export
    self.export_scene()
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/export_godot.py",
line 211, in export_scene
    self.export_object(obj, root_gd_node)
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/export_godot.py",
line 123, in export_object
    parent_gd_node)
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/converters/mesh.py",
line 26, in export_mesh_node
    escn_file, export_settings, obj, parent_gd_node
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/converters/physics.py",
line 205, in export_physics_properties
    while gd_node_ptr.get_type() not in PHYSICS_TYPES:
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/converters/physics.py",
line 92, in export_collision_shape
    node, convex=True
TypeError: cannot unpack non-iterable int object

Materials error:
[INFO]: Exporting scene: Scene
[INFO]: Exporting 16 objects
[INFO]: Exporting Blender object: floor
Traceback (most recent call last):
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/__init__.py",
line 198, in execute
    return export_godot.save(self, context, **keywords)
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/export_godot.py",
line 318, in save
    exp.export()
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/export_godot.py",
line 267, in export
    self.export_scene()
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/export_godot.py",
line 211, in export_scene
    self.export_object(obj, root_gd_node)
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/export_godot.py",
line 123, in export_object
    parent_gd_node)
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/converters/mesh.py",
line 45, in export_mesh_node
    mesh_id = mesh_exporter.export_mesh(escn_file, export_settings)
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/converters/mesh.py",
line 261, in export_mesh
    mesh
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/converters/mesh.py",
line 374, in generate_surfaces
    mat
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/converters/material/material.py",
line 53, in export_material
    escn_file, export_settings, bl_object, material
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/converters/material/material.py",
line 76, in generate_material_resource
    escn_file, export_settings, bl_object, material, mat
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/converters/material/script_shader/node_tree.py",
line 518, in export_script_shader
    shader_node_tree)
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/converters/material/script_shader/node_tree.py",
line 457, in parse_shader_node_tree
    converter.initialize_outputs()
  File
"/home/slapin/blender-2.80-linux-glibc217-x86_64/2.80/scripts/addons/io_scene_godot/converters/material/script_shader/node_converters.py",
line 429, in initialize_outputs
    assert isinstance(id_str, str) and id_str.isidentifier()
AssertionError

**Comment by Jason0214** [comment]
Thanks for the reporting, I think they are fixed now.

**Comment by SeleDreams** [comment]
![image](https://user-images.githubusercontent.com/16335601/93026473-774d1b00-f606-11ea-9a5f-355a1c39f4c5.png)

I am not sure it really is fixed as i am still getting this error myself

**Comment by Calinou** [comment]
@SeleDreams Please open a new issue for this.
