### ISSUE TITLE
Invisible mesh after export to godot

### ISSUE THREAD

**Issue by dodgyville** [godotengine/godot-blender-exporter#43]
Hi,

I have an fbx that I open in blender - it looks fine and the animation (of a woman standing idle) plays fine. When I open the escn file in godot created by this exporter, it all appears to load (the layers and animationplayer are there) but the meshes are invisible. The animation seems to play but I can't see the character. The meshes (body, shoes, clothes, etc) are visible in the inspector but not in the editor window. Any suggestions appreciated!

Here's the fbx file (~36mb)
https://drive.google.com/open?id=1-2tAMi7XbvjBJqJDYc8mPVgJZnRXR1B2

**Comment by Zireael07** [comment]
What was the scale/units in blender? Most likely your mesh is very very tiny in Godot.

**Comment by Jason0214** [comment]
in fbx the armature scale is 0.01, when I manually set it to 1 and export, the issue still exists, so it is a bug.

In Godot when I move all the mesh out of Skeleton node, they all got correctly visualized. Mostly likely the issue exists in bone weights exporting, (I remember Godot will not display a mesh under Skeleton but with no bone weights).

**Comment by dodgyville** [comment]
So from #44 are we saying that the bounding box of the parent node of mesh should be larger than the children AABBs?

I had a quick look at doing it in gdscript using a code snippet like this:
```
func _ready():
    var armature = get_node("Armature") # a Skeleton
    for mesh_instance in armature.get_children():
        var new_aabb = armature.get_aabb().merge(mesh_instance.get_aabb())
    armature.aabb = new_aabb

```

but Skeleton does not appear to have an bounding box at all

**Comment by Jason0214** [comment]
ah seems my fault,    yes,  Skeleton has no AABB, ( I will delete that comment

**Comment by Jason0214** [comment]
checked this issue again,

in the Armature node there is no bone listed
![image](https://user-images.githubusercontent.com/19422835/43750976-d313d45c-99af-11e8-99e9-0cc16e19280d.png)

when play the bone animation, you can see the bounding box move
![image](https://user-images.githubusercontent.com/19422835/43751156-9530ee30-99b0-11e8-9687-aa113abceded.png)


so I suppose the bone is imported but not get displayed, maybe some bone names cause issue?

**Comment by OBKF** [comment]
I have the same error when using Mixamo animations (a lot of people do) and not only this exporter if you try Better Collada or any other exporter it will happen.
I got this error when I imported the model (a lot of other similar errors and another ones that I couldn't get because of the short history on the windows console):
`
ERROR: get_bone_rest: Index p_bone=6 out of size (bones.size()=0)
   At: scene/3d/skeleton.cpp:496
ERROR: mesh_surface_get_index_array: Condition ' surface->index_array_len == 0 ' is true. returned: PoolVector<uint8_t>()
`

**Comment by OBKF** [comment]
Actually if you change the parent of the mesh to be the root it will show-up so the Skeleton is the problem here
![image](https://user-images.githubusercontent.com/12987951/47608563-d82dd300-da2f-11e8-8ca2-59b73f0e68ba.png)

**Comment by OBKF** [comment]
**_I made it work_**

![image](https://user-images.githubusercontent.com/12987951/47609684-ac1c4d00-da43-11e8-8b04-926341303b28.png)

![image](https://user-images.githubusercontent.com/12987951/47609758-4761f200-da45-11e8-9903-b4b9d8c69c1b.png)


The problem was in the naming of the armature, bones and vertex groups, I made a small Python script that you can run in Blender to change the names of the bones and vertex groups:


```
import bpy

for rig in bpy.context.selected_objects:
    if rig.type == 'ARMATURE':
        for mesh in rig.children:
            for vg in mesh.vertex_groups:
                #print(vg.name)
                new_name = vg.name
                new_name = new_name.replace("mixamorig:","")
                #print(new_name)
                rig.pose.bones[vg.name].name = new_name
                vg.name = new_name
        for bone in rig.pose.bones:
            #print(bone.name.replace("mixamorig:",""))
            bone.name = bone.name.replace("mixamorig:","")

for action in bpy.data.actions:
    print(action.name)
    fc = action.fcurves
    for f in fc:
        #print(f.data_path)    
        f.data_path = f.data_path.replace("mixamorig:","")

```

**Comment by Jason0214** [comment]
so the ':' is the illegal character for bone name right? if you are willing, you can make a PR to add a filtering for bone names [here](https://github.com/godotengine/godot-blender-exporter/blob/master/io_scene_godot/converters/armature.py#L110), it would be very simple and useful.   (Or I can do that for you

Thank you very much for spending time investigate this issue.

**Comment by OBKF** [comment]
You are welcome, I hope you can do the same for the Better Collada exporter as well as it's more used.

**Comment by akien-mga** [comment]
Fixed by #105.

**Comment by OBKF** [comment]
Well done :D

**Comment by dodgyville** [comment]
Yes, I don't want to add to everyone's emails but it's so great this is fixed!

**Comment by Favkis** [comment]
2023, bug still not fixed, item is invisible, even though AABB box shows like its okay 
![image](https://user-images.githubusercontent.com/46406204/230885841-755c3b28-95c6-4eef-bd23-7a04ccb1b773.png)

**Comment by ClintochX** [comment]
@Favkis Same is still have the sane issue, meshinstance is invisible when it has a skeleton.

I'm using bone names such as ss1, ss2, ss3, aa1, aa2, aa3...., origin, Transformer.

But I'm still having invisible sketal meshes
